
NUM_OF_DAYS = 730

SIM_PARAMS = "simulated_params"
T = "T0"
N_OF_PS = "NumOfPeriods"
LOG_PERIOD = "LogPeriod"
PERIOD = "Period"
ECC = "Eccentricity"
OMEGA = "OMEGA_rad"
K1_STR = "K1"
K2_STR = "K2"
GAMMA = "GAMMA"
RANGE = "Range"
SAMPLES = "Samples"
RVS = "RadialVelocities"
ERR_RVS = "RVErrors"
TS = "TimeStamps"
TS_DIFF = TS + "Diff"
M1 = "Mass1"
Q = "MassRatio"
INC = "Inclination"
NOISE_SIG = "noise_sigma"
NRV = "number_of_samples"
FEATURES = "features"
LABELS = "labels"
PLOT = "plot"

LMFIT_PARAMS = "lmfit_params"
SEARCH_REGION = "search_region"
MINI_METHOD = "minimization_method"
BIN_TIME = "BinTime"
INIT_VAL = "init_value"
MIN_VAL = "min_value"
MAX_VAL = "max_value"
VARY = "vary"

CORNER_PARAMS = "corner_params"
TRUTHS = "truths"
LN_SIGMA = "__lnsigma"
CONRER_METHOD = "method"
NAN_POLICY = "nan_policy"
BURN = "burn"
STEPS = "steps"
THIN = "thin"

TIME_STAMPS = "ts"
TRUE_ERRORS = "true_errs"
ERRORS = "errs"
RADIAL_VELS = "rvs"

MAX_MIN_DIFF = "maxMinDiff"
SIGNIFICANCE = "significance"

BEST_PERIOD = "bestPeriod"
BEST_PERIOD_POWER = "bestPeriodPower"
FALSE_ALARM_PROBABILITY = "fasleAlarmProbability"
FALSE_ALARM_LEVELS = "falseAlarmLevels"

PDC_BEST_PERIOD = "bestPeriodPDC"
PDC_BEST_PERIOD_POWER = "bestPeriodPowerPDC"
PDC_FALSE_ALARM_PROBABILITY = "falseAlarmProbabilityPDC"

NN_PERIOD = "nnPeriod"
NN_DECISION = "nnDecision"
NN_DECISION_PRE = "nnDecisionPreSigmoid"

LS_FREQS = "lombScargleFreqs"
LS_POWERS = "lombScarglePowers"